server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/photolibrary?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 810852437@qq.com
    password: lmkvzvvzivhobdje
    properties.mail.smtp.ssl.enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tuzx.demo.pojo

prop:
  img-folder: D:\Study\PhotoLibrary\img\
# 配置SpringMVC文件上传限制，默认1M。注意MB要大写，不然报错。SpringBoot版本不同，配置项不同

